# Generated by Django 5.1.2 on 2024-10-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlisting_highest_bid_auctionlisting_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
