# Generated by Django 5.1.2 on 2024-10-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='highest_bid',
        ),
    ]
